platform :ios, '9.0'
use_frameworks!

target 'PokemonMania' do

  pod 'SwiftLint'
  pod 'PhysicsEngine', :git => 'https://github.com/cs3217/2018-ps4-hliejun.git', :tag => '0.0.2'

  target 'PokemonManiaTests' do
    inherit! :search_paths
  end

  target 'PokemonManiaUITests' do
    inherit! :search_paths
  end

end
